### ISSUE TITLE
Signing error: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#116] opened 2024-06-16 19:55 UTC
A user [raised an issue in the Community repo](https://github.com/entropyxyz/community/discussions/23) about an error that popped up when trying to sign a message:

```plaintext
? Select Action Sign
? What would you like to do? Sign With Adapter

2024-06-14 10:28:44        REGISTRY: Unknown signed extensions ValidateConfirmRegistered found, treating them as no-effect
2024-06-14 10:28:44        API/INIT: RPC methods not decorated: chainSpec_v1_chainName, chainSpec_v1_genesisHash, chainSpec_v1_properties
? Please choose how you would like to input your message to sign: Text Input
? Enter the message you wish to sign (this will open your default editor): Received
msg to be signed: "Hello
"
Cannot read properties of undefined (reading 'startsWith')
? Return to main menu? (Y/n)
```

**Comment by mixmix** [comment] 2024-11-12 01:42
@johnnymatthews I've reviewed the JS stack (CLI, SDK) and all mentions of `startsWith` look safe.

I couldn't reproduce it with the latest release (v0.1.1)

![image](https://github.com/user-attachments/assets/c3651371-1012-4162-9ebc-d646fada0ba2)

---

Closing this for now, please feel free to re-open or question if you feel I've missed something

**Closed by mixmix** 2024-11-12 01:42 UTC
