### ISSUE TITLE
Check the balance of any account.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#115] opened 2024-06-16 16:45 UTC
The `Balance` command currently shows you the balance of your locally stored accounts. It'd be nice to be able to view the balance of any account, provided the user knows the public address of the account.

**Comment by rh0delta** [comment] 2024-07-10 17:39
We have made steps to allow for our users to check the balance of any account, however we have not made the necessary updates in the text interface to allow for this. These updates will be made a priority possibly next week.

CC: @frankiebee

**Comment by frankiebee** [comment] 2024-07-17 19:14
let make sure this also is seen in the cli not just the tui

**Comment by mixmix** [comment] 2024-11-12 01:45
Closing as a duplicate of https://github.com/entropyxyz/cli/issues/237

**Closed by mixmix** 2024-11-12 01:45 UTC
